### ISSUE TITLE
stack build fails

### ISSUE THREAD

**Issue by BlackCapCoder** [schell/odin#11]
Stack build fails with the following error message:
```
The same package name is used in multiple local packages

QuadTree used in:
- PLIndex "QuadTree-0.11.0"
- PLOther (PLRepo (Repo {repoUrl = "https://github.com/schell/QuadTree", repoCommit = "bd11166e50e5f2f4ade87613520aaf82e23cc9eb", repoType = RepoGit, repoSubdirs = "."}))
```

**Comment by schell** [comment]
Hey @BlackCapCoder - I just got back from vacation. QuadTree isn't used and I have a local branch with it removed that I'll push ASAP.

**Comment by schell** [comment]
@BlackCapCoder this should be fixed with new changes to `develop`. Keep in mind more work needs to be done to run the mapmaker. Most of the recent(ish) work I've been doing is in `odin-engine`' s widgets.
