### ISSUE TITLE
`stack build` fails due to relative paths outside of repo in stack.yaml

### ISSUE THREAD

**Issue by tripped** [schell/odin#2]
`stack build` fails with the following error:

```
/home/tripped/src/odin/../gelatin/gelatin-core: canonicalizePath: does not exist (No such file or directory)
```

It looks like this was introduced in [commit cd59ca10](https://github.com/schell/odin/commit/cd59ca109c0df2ea73fea04bb348795523a9068a), when the `stack.yaml` dependencies were replaced with relative paths outside of the repo. I was going to try fixing the dependencies myself and submitting a PR along with this issue, but as the change appears deliberate I'm not sure if there was a specific way you were planning to get the dependencies in a working order.

**Comment by schell** [comment]
Ah, yes - the dependencies are in flux but will be cleaned up shortly. You might want to try the part-one release https://github.com/schell/odin/releases/tag/part-one. I'll have `master` up and running soon enough, hopefully tonight.

**Comment by tripped** [comment]
Ah, cool; didn't see the tag. Thanks for the update.

**Comment by bwbaugh** [comment]
This appears have regressed again on master: [https://github.com/schell/odin/blob/e8f1bad7949a2adce204e1a4d3e65061ea0b334b/stack.yaml#L4]

**Comment by schell** [comment]
Yes, I keep doing this 👎. I'll get a patch in tomorrow and do my experimental work in a branch from now on.

**Comment by schell** [comment]
@bwbaugh please let me know if that last patch does it for you. Thanks :)
